behaviors:
  AgentKart:
    trainer_type: sac
    hyperparameters:
      buffer_init_steps: 1000
      init_entcoef: 0.7
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 200000
    time_horizon: 64
    summary_freq: 500